### ISSUE TITLE
Release Binaries on GitHub Releases

### ISSUE THREAD

**Issue by jonaprieto** [anoma/geb#51]
As part of the Juvix-Geb integration, we require access to Geb binaries. Currently, we are able to generate the binaries manually, but for the convenience of our CI process, we would like to request that Geb be tagged and released on GitHub Releases. As soon as we get this, we'd also update the Juvix codespaces to provide Geb as part of the toolchain. 

- [ ] Create a new release on GitHub Releases for each new version of Geb.
- [ ] Add, if possible, binaries for Ubuntu and macOS to each release.

PS.

For testing, one possible way to incorporate Geb in our GitHub CIs is something like this:

```
      - name: Install Geb binary
        uses: jonaprieto/action-install-gh-release@2
        with:
          repo: anoma/geb
          tag: latest
          binaries-location: bin # in case you put the binaries in a folder named `bin`
          cache: true
```
